version: '3.9'

services:

  client-1:
    image: ca
    shm_size: 0g
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
    stdin_open: true
    tty: true

  client-2:
    image: ca
    shm_size: 0g
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
    stdin_open: true
    tty: true

#  client-3:
#    image: ca
#    shm_size: 0g
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 1G
#    stdin_open: true
#    tty: true
#
#  client-4:
#    image: ca
#    shm_size: 0g
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 1G
#    stdin_open: true
#    tty: true
